// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'
import { withTimeout } from '@/lib/async-timeout'

const SESSION_LOOKUP_TIMEOUT_MS = 2_500

function findAccessToken(value: unknown): string | null {
  if (!value || typeof value !== 'object') return null
  const record = value as Record<string, unknown>
  if (typeof record.access_token === 'string') return record.access_token
  if (record.currentSession) return findAccessToken(record.currentSession)
  if (record.session) return findAccessToken(record.session)
  return null
}

function readCachedAccessToken(): string | null {
  if (typeof window === 'undefined') return null
  try {
    for (let i = 0; i < window.localStorage.length; i += 1) {
      const key = window.localStorage.key(i)
      if (!key || !key.startsWith('sb-') || !key.endsWith('-auth-token')) continue
      const raw = window.localStorage.getItem(key)
      if (!raw) continue
      const token = findAccessToken(JSON.parse(raw))
      if (token) return token
    }
  } catch {
    return null
  }
  return null
}

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const cachedToken = readCachedAccessToken()
    const token = await withTimeout(
      supabase.auth.getSession().then(({ data }) => data.session?.access_token ?? null),
      SESSION_LOOKUP_TIMEOUT_MS,
      'Server function auth token lookup timed out',
    ).catch((error) => {
      console.warn('[server-fn-auth] token lookup failed; using cached token if available', error)
      return cachedToken
    })
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
